apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptimekuma.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "uptimekuma.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "uptimekuma.name" . }}
    spec:
      containers:
        - name: uptimekuma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "uptimekuma.fullname" . }}
